name: textgb
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  adaptive_theme: ^3.7.0
  country_picker: ^2.0.27
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  shared_preferences: ^2.5.3
  flutter_riverpod: ^2.6.1
  uuid: ^4.5.1
  image_cropper: ^9.1.0
  pinput: ^5.0.1
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  permission_handler: ^12.0.0+1
  cached_network_image: ^3.4.1
  timeago: ^3.7.0
  path_provider: ^2.1.5
  animate_do: ^3.3.9
  date_format: ^2.0.9
  video_player: ^2.9.5
  get: ^4.6.1
  git: ^2.3.2
  github: ^9.24.0
  file_picker: ^10.1.2
  crypto: ^3.0.6
  http: ^1.3.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  freezed_annotation: ^3.0.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  flutter_html: ^3.0.0
  flutter_image_compress: ^2.4.0
  

  html: ^0.15.4                 # Parse HTML for link previews
  image_size_getter: ^2.1.2     # Get image dimensions
  visibility_detector: ^0.4.0+2 # Detect when widgets are visible on screen
  collection: ^1.18.0           # Utility for collections
  flutter_staggered_grid_view: ^0.7.0 # For media grid layout
  provider: ^6.1.5
  riverpod_generator: ^2.6.5
  riverpod_annotation: ^2.6.1
  flutter_local_notifications: ^19.2.0
  encrypt: ^5.0.3
  carousel_slider: ^5.0.0
  wakelock_plus: ^1.3.2
  confetti: ^0.8.0
  flutter_cache_manager: ^3.4.1
  dio: ^5.8.0+1
  device_info_plus: ^11.3.0
  video_thumbnail: ^0.5.6
  image: ^4.5.4
  gal: ^2.3.1
  share_plus: ^11.1.0
  swipe_to: ^1.0.6
  flutter_svg: ^2.2.0
  flutter_video_caching: ^0.3.11
  flutter_contacts: ^1.1.9+2
  web_socket_channel: ^3.0.3
  path: ^1.8.3
  ffmpeg_kit_flutter_new: ^4.0.0
  go_router: ^16.1.0









  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6           # Added for code generation
  json_serializable: ^6.9.5

dependency_overrides:
  path: 1.8.3 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
