name: textgb
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  adaptive_theme: ^3.7.0
  country_picker: ^2.0.27
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  shared_preferences: ^2.5.3
  flutter_riverpod: ^2.6.1
  uuid: ^4.5.1
  cloud_firestore: ^5.6.6
  image_cropper: ^9.1.0
  pinput: ^5.0.1
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  permission_handler: ^12.0.0+1
  cached_network_image: ^3.4.1
  timeago: ^3.7.0
  flutter_sound_record: ^3.3.2
  path_provider: ^2.1.5
  emoji_picker_flutter: ^4.3.0
  audioplayers: ^6.4.0
  flutter_chat_reactions: ^0.1.1
  animate_do: ^3.3.9
  date_format: ^2.0.9
  grouped_list: ^6.0.0
  swipe_to: ^1.0.6
  chewie: ^1.11.1
  video_player: ^2.9.5
  get: ^4.6.1
  video_compress: ^3.1.4
  git: ^2.3.1
  github: ^9.24.0
  story_view: ^0.16.5
  flutter_colorpicker: ^1.1.0
  flutter_contacts: ^1.1.9+2
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.10+1
  file_picker: ^10.1.2
  share_plus: ^10.1.4
  photo_view: ^0.15.0
  crypto: ^3.0.6
  http: ^1.3.0
  intl: ^0.19.0
  photo_manager: ^3.6.4
  url_launcher: ^6.3.1
  freezed_annotation: ^3.0.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  flutter_html: ^3.0.0
  flutter_image_compress: ^2.4.0
  

  html: ^0.15.4                 # Parse HTML for link previews
  image_size_getter: ^2.1.2     # Get image dimensions
  visibility_detector: ^0.4.0+2 # Detect when widgets are visible on screen
  firebase_messaging: 15.2.5   # Optional: For status notifications
  collection: ^1.18.0           # Utility for collections
  flutter_staggered_grid_view: ^0.7.0 # For media grid layout
  provider: ^6.1.5
  riverpod_generator: ^2.6.5
  riverpod_annotation: ^2.6.1
  flutter_local_notifications: ^19.2.0
  encrypt: ^5.0.3
  video_thumbnail: ^0.5.6
  carousel_slider: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6           # Added for code generation
  json_serializable: ^6.9.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
